name: UL Helper

on:
  workflow_dispatch:

jobs:
  Prepare-Env:
    runs-on: ubuntu-latest
    steps:

      - name: Install packages,setup & download
        run: |
          sudo apt update
          sudo apt install wget -y
          wget https://github.com/ReVanced/revanced-manager/releases/download/v1.20.1/revanced-manager-v1.20.1.apk
          ls
          echo 'Done'

      - name: Upload to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: /*
          message: "Upload Successful."
